### ISSUE TITLE
docker-compose shows white screen

### ISSUE THREAD

**Issue by SOIT-SF** [icescrum/iceScrum-docker#6]
When I try launching with docker-compose up -d  I get a white screen.
Here is the compose file.

```
version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=icescrum
      - MYSQL_ROOT_PASSWORD=test
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  icescrum:
    image: icescrum/icescrum
    volumes:
      - icescrum:/root
    ports:
      - "8080:8080"
    depends_on:
      - mysql


volumes:
  mysql:
  icescrum: 
```
docker logs 
``
iceScrum` is running!
iceScrum runs inside a Docker container so it cannot know its external URL. It should look like http://<docker-host>:<mapped-port>/icescrum.
If you use a VM (e.g. Docker Machine) the docker host is the VM IP, otherwise it's localhost or your machine IP.
To stop iceScrum, use docker stop. To restart, use docker restart.
``
